In [5]:
import pandas as pd
df = pd.read_csv('spam.csv')
df.head()


Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [36]:
df.groupby('Category').describe()

spam                                   
           count mean  std  min  25%  50%  75%  max
Category                                           
ham       4825.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
spam       747.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

In [ ]:
#convert message and category into number.

In [15]:
df['spam'] = df['Category'].apply(lambda x:1 if x == 'spam' else 0)  #converting category column into number by using lambda function.
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.Message,df.spam, test_size = 0.3)

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
m = v.fit_transform(x_train.values)
m.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(m, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [30]:
email = ['hey, will you come tomorrow?', 'exclusive offer for you on credit card']
email_v = v.transform(email)
model.predict(email_v)

array([0, 1], dtype=int64)

In [32]:
m = v.transform(x_test)
model.score(m,y_test)

0.986244019138756

In [ ]:
# using pipeline trick

In [33]:
from sklearn.pipeline import Pipeline 
clf = Pipeline([('v',CountVectorizer()),
                ('nb', MultinomialNB())
               ])
clf.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('v',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [34]:
clf.score(x_test, y_test)

0.986244019138756

In [35]:
clf.predict(email)

array([0, 1], dtype=int64)